GET http://localhost:3000/subscribers

### 

GET http://localhost:3000/subscribers/5db4ac75f30cf20bccab1463

###


POST http://localhost:3000/subscribers
content-type: application/json

{
    "name": "Daniel",
    "subscribedToChannel":"Pixelagil"
}

###

PATCH http://localhost:3000/subscribers/5db4b3a6d1ea4b20682fd0dc
content-type: application/json

{
    "name": "Daniel Test",
    "subscribedToChannel":"Pixelagil"
}

###

DELETE http://localhost:3000/subscribers/5db4ac75f30cf20bccab1463